dist: xenial
branches:
  only:
    - master
language: csharp
solution: eform-WorkOrderBase/Microting.WorkOrderBase.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.WorkOrderBase.sln
  - dotnet test -v n Microting.WorkOrderBase.Tests/Microting.WorkOrderBase.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.WorkOrderBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-WorkOrderBase/Microting.WorkOrderBase/artifacts/Microting.WorkOrderBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
